export const GET_ANNONCES_SUCCESS = 'GET_ANNONCES_SUCCESS';
export const GET_ANNONCES_LOAD = 'GET_ANNONCES_LOAD';
export const GET_ANNONCES_FAIL = 'GET_ANNONCES_FAIL';
export const GET_ANNONCE_SUCCESS = 'GET_ANNONCE_SUCCESS';
export const CLEAR_ERRORS = "CLEAR_ERRORS";
