export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS';
export const GET_COMMENT_LOAD = 'GET_COMMENT_LOAD';
export const GET_COMMENT_FAIL = 'GET_COMMENT_FAIL';
export const GET_COMMENT = 'GET_COMMENT';
